/// Flutter icons RPiIoTIcons2_0
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RPiIoTIcons2_0
///      fonts:
///       - asset: fonts/RPiIoTIcons2_0.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

// ignore: camel_case_types
class RPiIoTIcons2_0 {
  RPiIoTIcons2_0._();

  static const _kFontFam = 'RPiIoTIcons2_0';
  static const _kFontPkg = null;

  static const IconData fan_svg = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
